<?php

namespace Devian\FrontendForms\Fields;

/**
 * Class PhoneField
 * @package Devian\FrontendForms\Field
 */
class PhoneField extends AbstractField
{

    public const CODE = 'phone.field';


    /**
     * @inheritDoc
     */
    public function getSubType(): string
    {
        return 'phone';
    }


    /**
     * @inheritDoc
     */
    public function getType(): string
    {
        return 'string';
    }

    /**
     * @inheritDoc
     */
    public function getFieldCode(): string
    {
        return self::CODE;
    }

    /**
     * @inheritDoc
     */
    protected function riseFromSavedData()
    {
        // TODO: Implement riseFromSavedData() method.
    }

    /**
     * @inheritdoc
     */
    public function setValue($value)
    {
        $value = preg_replace('#[^0-9]#', '', $value);
        parent::setValue($value); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function validate(): bool
    {
        return preg_match('#^[0-9]*$#', $this->fieldValue);
    }


}
